[project]
name = "werewolf-notebook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.2.0",
    "langchain-community>=0.4.1",
    "langgraph>=1.0.5",
    "notebook>=7.5.1",
]
